feat: make navbar sticky
devs-in-tech/DevsInTech pull request #140
Opened 2023-05-23 16:59 UTC by suryanshsoni120

## Fixes Issue

 Closes #121

2023-05-23 19:22 UTC, md-abid-hussain commented
There is an issue with the style.
![Screenshot (52)](https://github.com/devs-in-tech/DevsInTech/assets/101964499/04ea7844-900c-43af-a185-0ddb32555988)

2023-05-23 19:29 UTC, md-abid-hussain requested changes
There is an issue with the style. The button are appearing over the header.
![Screenshot (52)](https://github.com/devs-in-tech/DevsInTech/assets/101964499/5990dfe3-b408-4198-b495-3c476719a98c)

2023-05-24 09:20 UTC, himanshu1221 approved these changes

2023-05-29 13:49 UTC, AbhiPatel10 commented
> There is an issue with the style. The button are appearing over the header. ![Screenshot (52)](https://user-images.githubusercontent.com/101964499/240398970-5990dfe3-b408-4198-b495-3c476719a98c.png)

In local It's works fine.

2023-05-29 13:50 UTC, AbhiPatel10 approved these changes

2023-05-29 13:50 UTC, AbhiPatel10 approved these changes

2023-05-29 13:50 UTC, AbhiPatel10 approved these changes

2023-05-29 13:50 UTC, merged