feat: add counter effect
devs-in-tech/DevsInTech pull request #146
Opened 2023-05-23 21:03 UTC by mohammadshaad

## Fixes Issue 
Closes #126 

## Changes proposed

Added the counter effect to the numbers in the homepage stats section

## Screenshots

<img width="1045" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/89409389/5dc6e0d7-a043-4315-9d62-9df488ed5864">

## Note to reviewers

2023-05-23 21:04 UTC, mohammadshaad commented
@himanshu1221 kindly review and merge the PR

2023-05-24 09:17 UTC, himanshu1221 requested changes

2023-05-24 09:17 UTC, himanshu1221 commented on src/components/HomePage/stats/index.jsx
> +    }, 100); // Adjust the interval duration as needed
Hey @mohammadshaad it would be great if you increase the time for the effect as it take a lot time to reach 600+

2023-05-24 09:18 UTC, mohammadshaad commented on src/components/HomePage/stats/index.jsx
> +    }, 100); // Adjust the interval duration as needed
yeah sure

2023-05-24 09:21 UTC, mohammadshaad commented
@himanshu1221 now check please

2023-05-25 13:21 UTC, mohammadshaad commented
@himanshu1221 please merge the PR

2023-05-25 13:22 UTC, himanshu1221 approved these changes
LGTM :+1:

2023-05-25 13:23 UTC, merged