[fix] Add a checkbox for GSSoC contributors
devs-in-tech/DevsInTech pull request #197
Opened 2023-06-01 13:27 UTC by CBID2

## Fixes Issue
Closes #181 

## Changes proposed

I added a checkbox for GSSOC’23 contributors to confirm their participation in the program. 

## Screenshots

![GSSOC checkbox in Docs issue template](https://github.com/devs-in-tech/DevsInTech/assets/105683440/c349222c-4e33-493a-9db1-04db2b67aa02)

## Note to reviewers
I would get errors when I try putting the checkbox in the Bug Report and Feature Request issue templates, so feedback on those two forms would be great.

2023-06-01 13:46 UTC, himanshu1221 requested changes
Hey @CBID2 I am unable to find `feature` issue template and another issue template apart from these follows and there is a label that is not working in the bug issue template 

![Screenshot from 2023-06-01 19-10-07](https://github.com/devs-in-tech/DevsInTech/assets/32031706/2537096b-e37f-4bc7-827c-6cac7d09aa98)

![Screenshot from 2023-06-01 19-12-31](https://github.com/devs-in-tech/DevsInTech/assets/32031706/238be4bc-d563-4b7e-8934-91237d7cdcdf)

2023-06-01 13:50 UTC, CBID2 commented
> Hey @CBID2 I am unable to find `feature` issue template and another issue template apart from these follows and there is a label that is not working in the bug issue template
> 
> ![Screenshot from 2023-06-01 19-10-07](https://user-images.githubusercontent.com/32031706/242616805-2537096b-e37f-4bc7-827c-6cac7d09aa98.png)
> 
> ![Screenshot from 2023-06-01 19-12-31](https://user-images.githubusercontent.com/32031706/242616813-238be4bc-d563-4b7e-8934-91237d7cdcdf.png)

Hi @himanshu1221! I made the change to the bug report and feature request template. I just have trouble adding the checkbox

2023-06-28 07:17 UTC, Susmita-Dey requested changes
Also, update your branch

2023-06-28 07:17 UTC, Susmita-Dey commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +description: "Have any new idea or new feature for Devsintech? Please request!"
Change the text "Devsintech" to "DevsInTech"

2023-06-28 13:46 UTC, Susmita-Dey commented
Hey @himanshu1221 kindly check this PR once.

2023-07-02 09:12 UTC, prnvtripathi approved these changes
LGTM :)

2023-07-03 03:54 UTC, merged