Hover button, font size improvement
devs-in-tech/DevsInTech pull request #229
Opened 2023-06-06 08:14 UTC by ojasaklechayt

Fixes: #210 

### What's the style idea?

Details:
1. Text Size Deceased.
2. Navbar Names Hover Improvement.
3. Content added for " What is DevsInTech Community? ".

### Add screenshots

Before:
![image](https://github.com/devs-in-tech/DevsInTech/assets/90605717/66f09ec1-f892-410a-96aa-9c0861ad3461)
![image](https://github.com/devs-in-tech/DevsInTech/assets/90605717/94b21c50-7a10-46cf-9a25-87d86320d9ae)

After:
![image](https://github.com/devs-in-tech/DevsInTech/assets/90605717/504c6088-2203-4f13-b89a-5ac265bb5bc3)
![image](https://github.com/devs-in-tech/DevsInTech/assets/90605717/e5e7cb21-60b1-4c85-b7a3-b493620c5258)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

2023-06-08 05:46 UTC, himanshu1221 requested changes
Hey @ojasaklechayt there are some unwanted spaces between text kindly check fix them 

![Screenshot from 2023-06-08 11-14-57](https://github.com/devs-in-tech/DevsInTech/assets/32031706/d936adad-46a8-4e8c-8a00-a2cdee50634d)

2023-06-08 05:46 UTC, himanshu1221 requested changes
Hey @ojasaklechayt there are some unwanted spaces between text kindly check fix them 

![Screenshot from 2023-06-08 11-14-57](https://github.com/devs-in-tech/DevsInTech/assets/32031706/d936adad-46a8-4e8c-8a00-a2cdee50634d)

2023-06-08 06:01 UTC, ojasaklechayt commented
> Hey @ojasaklechayt there are some unwanted spaces between text kindly check fix them
> 
> ![Screenshot from 2023-06-08 11-14-57](https://user-images.githubusercontent.com/32031706/244276157-d936adad-46a8-4e8c-8a00-a2cdee50634d.png)

okay ser I will look into it

2023-06-08 10:39 UTC, ojasaklechayt commented
> > Hey @ojasaklechayt there are some unwanted spaces between text kindly check fix them
> > ![Screenshot from 2023-06-08 11-14-57](https://user-images.githubusercontent.com/32031706/244276157-d936adad-46a8-4e8c-8a00-a2cdee50634d.png)
> 
> okay ser I will look into it

done ser

2023-06-20 19:25 UTC, ojasaklechayt commented
@Susmita-Dey @himanshu1221 any updates on this ?

2023-06-26 13:36 UTC, ojasaklechayt commented
@Susmita-Dey @himanshu1221 ?

2023-06-28 07:19 UTC, Susmita-Dey requested changes
Hey @ojasaklechayt Kindly fix the merge conflict and I can still see some unwanted spaces in the above ss

2023-06-28 13:49 UTC, Susmita-Dey commented on src/utils/helper/validation.js
> +export const Mobile_REGEX = /^[0-9]{10}$/;
What's the usecase of this file?

2023-06-28 15:25 UTC, ojasaklechayt commented on src/utils/helper/validation.js
> +export const Mobile_REGEX = /^[0-9]{10}$/;
I feel this is for chatbot. It's not my code

2023-06-28 15:47 UTC, Susmita-Dey commented
Hey @ojasaklechayt Ping me when this PR is ready to merge(you're done with the tasks)

2023-06-28 15:52 UTC, Susmita-Dey commented
> Shall I remove this validation.js code ?
Yes. I don't see it's use case. Also, it's don't related to your issue/PR

2023-06-28 15:59 UTC, ojasaklechayt commented
@Susmita-Dey I feel PR is ready. Can you please check once ?

2023-06-28 17:51 UTC, Susmita-Dey requested changes
![image](https://github.com/devs-in-tech/DevsInTech/assets/79099734/dae8ec97-cf9d-4005-aa79-b62b7d0b2c88)

Make the text short in footer as much as possible

2023-06-29 04:34 UTC, Susmita-Dey commented
Hey @ojasaklechayt Also, don't forget to resolve merge conflicts

2023-06-29 09:13 UTC, ojasaklechayt commented
@Susmita-Dey  Resolved the conflicts and made the text shorter

2023-06-29 11:58 UTC, Susmita-Dey approved these changes
LGTM

2023-06-29 11:59 UTC, merged