feat: Add testimonial carousel
devs-in-tech/DevsInTech pull request #31
Opened 2023-04-27 19:04 UTC by prnvtripathi

## Fixes Issue
 closes #25 
## Changes proposed

- made a testimonial carousel

2023-05-12 15:05 UTC, prnvtripathi commented
Working on it 😁

2023-05-14 14:03 UTC, prnvtripathi commented
hey @AbhiPatel10 , please check the new changes made and do let me know if any suggestions are there :)

2023-05-14 17:05 UTC, AbhiPatel10 requested changes

2023-05-14 17:05 UTC, AbhiPatel10 commented on src/pages/index.js
> +import Navbar from "@/components/Navbar";
Remove this line

2023-05-14 17:05 UTC, AbhiPatel10 commented on src/components/testimonial.js
Add this component in home page and also add header component with testimonial section Name

2023-05-16 08:07 UTC, prnvtripathi commented on src/components/testimonial.js
I added the component in the home page, where do I have to add header component?

2023-05-18 08:18 UTC, AbhiPatel10 commented on src/components/testimonial.js
In Your component.

2023-05-20 15:01 UTC, himanshu1221 commented
@prnvtripathi any update on this ?

2023-05-20 15:02 UTC, prnvtripathi commented
I've done all the updates, except the header thing, i am not able to understand what to do in it.

2023-05-20 15:38 UTC, himanshu1221 commented
Share any screenshots if possible

2023-06-03 09:53 UTC, AbhiPatel10 approved these changes

2023-06-03 15:14 UTC, prnvtripathi reviewed
@himanshu1221 please approve the changes, as it is required to merge the changes

2023-06-05 09:19 UTC, himanshu1221 approved these changes
LGTM:+1:

2023-06-05 09:19 UTC, merged