feat: implement responsiveness for contributors page
devs-in-tech/DevsInTech pull request #347
Opened 2023-07-04 12:49 UTC by karthiknadar1204

## Fixes Issue #344 

## Changes proposed

## Screenshots

## Note to reviewers

2023-07-04 12:58 UTC, Susmita-Dey requested changes
Not looking good for iPad devices and large screens
![image](https://github.com/devs-in-tech/DevsInTech/assets/79099734/959a0a61-f3dd-427a-bb45-7a1e2a4a1bff)


Also, for normal laptop devices, the buttons don't have margins around it and the color on hover is also not looking good. It also seems like there's no hierarchy in font sizes which results in bad UX. Fix it

2023-07-04 12:59 UTC, karthiknadar1204 commented
will do it right away @Susmita-Dey

2023-07-04 12:59 UTC, Susmita-Dey commented
I've having exams so won't be active to help you out or merge PR, if you need help them join our Discord server. Link in the website. Also, @devs-in-tech/devsintech-web-team kindly check it

2023-07-04 16:02 UTC, karthiknadar1204 commented
@Susmita-Dey Done with the changes for the larger screen sizes,pushing the changes in a bit

2023-07-04 16:05 UTC, karthiknadar1204 commented
Please check whenever free

2023-07-05 05:03 UTC, Susmita-Dey requested changes

2023-07-05 05:03 UTC, Susmita-Dey commented on src/pages/Contributors.js
> +
Can you remove this duplicate lines which are commented?

The file would look clean

2023-07-05 06:14 UTC, karthiknadar1204 commented
yes, was testing the new code so had commented out, will do and push changes in a bit

2023-07-05 06:23 UTC, karthiknadar1204 commented
Done, could you please check now

2023-07-05 13:41 UTC, Susmita-Dey approved these changes
LGTM. Thanks for contributing:)

2023-07-05 13:54 UTC, merged