feat: add back to top button
devs-in-tech/DevsInTech pull request #87
Opened 2023-05-20 16:54 UTC by suryanshsoni120

Closes #82

## Changes proposed

added a new component back to top button

2023-05-21 06:45 UTC, himanshu1221 approved these changes
LGTM :+1:

2023-05-22 07:19 UTC, AbhiPatel10 requested changes

2023-05-22 07:19 UTC, AbhiPatel10 commented on src/components/ScrollToTop.jsx
> +        onClick={scrollToTop}
background colour not applied ------ bg-#212428  Change with bg-[#212428]

2023-05-22 11:46 UTC, AbhiPatel10 commented
Looks good, Thank you for your contribution @suryanshsoni120

2023-05-22 11:47 UTC, AbhiPatel10 approved these changes

2023-05-22 11:47 UTC, merged